Publish junit report, enable junit in profile
Add a nextest profile that outputs a junit file, add a junit action and
use the ci profile with nextest

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -69,4 +69,9 @@ jobs:
         name: Doc tests
         run: cargo test --doc --features better-build-info,static-grammar-libs,dynamic-grammar-libs
       - name: Tests
-        run: cargo nextest run --locked --target ${{ matrix.job.target }} --features better-build-info,static-grammar-libs,dynamic-grammar-libs
+        run: cargo nextest run --locked --target ${{ matrix.job.target }} --features better-build-info,static-grammar-libs,dynamic-grammar-libs --profile ci
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/nextest/ci/junit.xml'
