ci: Update Github actions to use more recent APIs (#617)
* ci: Update Github actions to use more recent APIs

This uses cargo nextest and dtolnay's rust toolchain action. The old
`actions-rs` Github actions have been deprecated and unmaintained.

* fix: Remove redundant statement

We already pull in the rust toolchain above and it's invalid to have a
`uses` and `runs` statement in the same block.

* Update uses directive

Previous thing was malformed

* Add components, env var

* Remove redundant env vars

Didn't realize I'd already set it above

* Use talk-e's steps, simplify flow

- We don't need to check the build and also tests, because you need to
  build the binary to test anyways
- Use talki-e's cross compilation steps

* Add aarch64 windows target, fix arm target

* Remove unused parameter

We don't use it anymore

* Install nextest in CI

* Don't use cross toolchain with non linux targets

Turns out it's not supported

* Try to fix conditions

* Put conditional in braces

* Specify toolchain

* Only run doctests on one target

We can't run doctests in the cross toolchain

* Move conditional statement

* disable arm7

Seems like it's not recognized as a valid target

* Publish junit report, enable junit in profile

Add a nextest profile that outputs a junit file, add a junit action and
use the ci profile with nextest

* Use target name

So junit reports don't all have the same name which can be a bit
confusing.

* Break a test

Just for fun to test out the junit annotation action.

* Revert "Break a test"

This reverts commit 9d80a1c3ab171569a31a33376f162d09a173b97f.

* Remove commented out code

* fix: Remove windows aarch64 target

* Install cross toolchains correctly

* Add more release targets

* Fix target triplets

* Add more targets

* Set darwin target

* Load rust cache before other steps

* Use talk-e's upload action

* Add checksum

* Add asset

* Use install action for cargo deb

* Fix install action

* Remove unnecessary steps

* Split up install step

* Fix install action version

* Use production profile

* Don't upload git-diffsitter

It seems like the action tries to upload it for every target in the
matrix

* Build the binary before running cargo deb

* set target directory

* Remove unneeded line

* fix env var declaration

* Add env var for cargo terminal colors

* Install gh cli

* Don't install CLI action

* Put command into 1 line

* Specify target in command

* Remove redundant step

Don't need to build the binary twice

* Use newer version of deb

* Remove homebrew step

Will split this to another action

* Build the production binary

Apparently for cross tools it's recommended to build separately.

* Copy from the correct target dir

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -16,60 +16,55 @@ jobs:
     strategy:
       matrix:
         job:
-          - { os: macos-latest, target: x86_64-apple-darwin, use-cross: false }
+          - { os: macos-latest, target: x86_64-apple-darwin }
           - {
               os: ubuntu-latest,
               target: x86_64-unknown-linux-gnu,
-              use-cross: false,
             }
           - {
               os: ubuntu-latest,
               target: i686-unknown-linux-gnu,
-              use-cross: true,
-            }
-          - {
-              os: ubuntu-latest,
-              target: arm-unknown-linux-gnueabihf,
-              use-cross: true,
             }
           - {
               os: ubuntu-latest,
               target: aarch64-unknown-linux-gnu,
-              use-cross: true,
             }
           - {
               os: windows-latest,
               target: x86_64-pc-windows-msvc,
-              use-cross: false,
             }
     steps:
       - uses: actions/checkout@v3
         with:
           submodules: true
-      - name: Install Rust
-        uses: actions-rs/toolchain@v1
+      - if: ${{ matrix.job.os == 'ubuntu-latest' }}
+        name: Install cross-compilation tools
+        uses: taiki-e/setup-cross-toolchain-action@v1
         with:
-          toolchain: stable
           target: ${{ matrix.job.target }}
-          profile: minimal
-          override: true
+      - if: ${{ matrix.job.os != 'ubuntu-latest' }}
+        name: Install native Rust toolchain
+        uses: dtolnay/rust-toolchain@master
+        with:
+          targets: ${{ matrix.job.target }}
+          components: rustfmt,clippy
+          toolchain: stable
       - uses: Swatinem/rust-cache@v2
         with:
-          key: ${{ matrix.job.target }}
+          key: ci-${{steps.toolchain.outputs.name}}
+      - uses: taiki-e/install-action@v2
+        with:
+          tool: nextest
       - name: Check formatting
-        uses: actions-rs/cargo@v1
+        run: cargo fmt --all -- --check
+      - if: ${{ matrix.job.target == 'x86_64-unknown-linux-gnu' }}
+        name: Doc tests
+        run: cargo test --doc --features better-build-info,static-grammar-libs,dynamic-grammar-libs
+      - name: Tests
+        run: cargo nextest run --locked --target ${{ matrix.job.target }} --features better-build-info,static-grammar-libs,dynamic-grammar-libs --profile ci
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
         with:
-          command: fmt
-          args: --all -- --check
-      - name: Build
-        uses: actions-rs/cargo@v1
-        with:
-          command: build
-          use-cross: ${{ matrix.job.use-cross }}
-          args: --locked --target ${{ matrix.job.target }} --features better-build-info,static-grammar-libs,dynamic-grammar-libs
-      - name: Unit tests
-        uses: actions-rs/cargo@v1
-        with:
-          command: test
-          use-cross: ${{ matrix.job.use-cross }}
-          args: --locked --target ${{ matrix.job.target }} --verbose --features better-build-info,static-grammar-libs,dynamic-grammar-libs
+          report_paths: '**/target/nextest/ci/junit.xml'
+          check_name: diffsitter tests ${{ matrix.job.target }}
